### ISSUE TITLE
Change metrics name to be usable as a variable in Grafana

### ISSUE THREAD

**Issue by simonszu** [kinduff/csgo_exporter#1]
Hi, 
just a suggestion: Instead of naming each metrics like `total_kills_ak47` it would be a good idea to maybe add more labels like `kills` and `ak47`. This enables grafana to define these names as variable values, and enables me as a dashboard creator to get a neat dropdown where i can select a certain weapon and see its stats. 
The same goes for the map selection.

**Comment by kinduff** [comment]
This is a great idea! Any other improvements you would like to add? I've been searching for time to make a dashboard for this, and would like to have your contribution.

**Comment by simonszu** [comment]
This is the first thing i noticed. If you notify me once this is implemented, i will set up a first dashboard draft with weapon stats. 
What i noticed: You put very many stats just in the `csgo_stats_metric`metric and are relying heavily on the name setting. Lets assume i want a sum of all my kills. Currently this is only possible with adding all weapon kill fields manually. So i would suggest that you do some abstraction, like `csgo_weapon_kills{name="ak47"}` and if i want to have just a sum of all my kills i would just add all `csgo_weapon_kills` elements, with omitting the name. 

Same for the maps, weapon hits, and weapon shots fired. But keep the old metrics vector for backwards compatibility. 

I also noticed that you only have map stats for the gun games. Doesn't the API provide stats for the official matchmaking maps? I play almost only Mirage, Inferno, Overpass, but these maps arent in the list. 

If you want to add additional candy and if the steam api allows it: Player inventories. Maybe even with getting the average buy and sell price from csgostash.com, so players which are doing case investments can see their valuables as well.

That's it for now, i think.

**Comment by kinduff** [comment]
@simonszu I created a project to address some of your ideas and suggestions, will keep it up to date in case you want to see some progress. Closing this.
