### ISSUE TITLE
[dashboard] Last match CT/T Wins is not what one would expect

### ISSUE THREAD

**Issue by colega** [kinduff/csgo_exporter#30]
I'd expect `CT Wins` and `T wins` to be the amount of rounds that I won being CT or T in that match, but instead, that's just the match itself stats, which is pretty useless here IMO.

See:

![image](https://user-images.githubusercontent.com/1511481/123777750-cd0e5d80-d8d0-11eb-9651-b5f249031dde.png)

While that match was https://csgostats.gg/match/38232470

![image](https://user-images.githubusercontent.com/1511481/123777791-d4ce0200-d8d0-11eb-9820-cf90e456e871.png)

I think it's more useful to render the `csgo_last_match_metric{type="wins"}` as _wins_ and `csgo_last_match_metric{type="wins"} - csgo_last_match_metric{type="rounds"}` as _losses_ there. WDYT?

**Comment by kinduff** [comment]
@colega I'm pretty bummed about this, Valve considers the warm up matches as rounds, and they include them all in the metric. I currently have no way to know which are rounds from the game, and rounds from the warm up matches.

_valveplsfix_

The alternative would be to actually parse the demos, but that's a lot of work, but it's worth imho.

**Comment by kinduff** [comment]
> I think it's more useful to render the csgo_last_match_metric{type="wins"} as wins and csgo_last_match_metric{type="wins"} - csgo_last_match_metric{type="rounds"} as losses there. WDYT?

Missed this part of the message. Can't read today apparently.

I like the idea, want to do a test and post a screenshot?

**Comment by colega** [comment]
I made a proposal in https://github.com/kinduff/csgo_exporter/pull/33 PTAL.
