### ISSUE TITLE
Label metrics with `player_name` too

### ISSUE THREAD

**Issue by colega** [kinduff/csgo_exporter#31]
If there were multiple exporters running, the player ID isn't very human friendly.  Since we have it, we could add a `player_name` label too.

A next step would be to have that `player_name` as template variable in the dashboard, so one could set up a Grafana for his entire team/clan/etc.

**Comment by kinduff** [comment]
@colega Thanks for reporting. This is actually a bug, we used to override the `player` variable if the `STEAM_NAME` was provided. I will add both, but I need to consider the advantages since I need to do a reverse lookup to convert from SteamID to SteamName.

**Comment by colega** [comment]
I think both can be useful, and since this doesn't add cardinality I'd try to export both labels.
